sudo:  required

language: python
python:
  - "3.8"

services:
   - postgresql
   
addons:
  chrome: stable

env:
  global:
  - DATABASE_URI=postgres://postgres:@localhost:5432/testdb

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt  
  - sudo apt-get install -y chromium-chromedriver python3-selenium

before_script:
  - psql -c 'create database testdb;' -U postgres
  - chromedriver --version
  - gunicorn --log-level=info --bind=127.0.0.1:5000 service:app &
  - sleep 5
  - curl -I http://localhost:5000/

# command to run tests
jobs:
  include:
    - stage: Test
      name: TDD
      script: nosetests
      after_success: codecov

    - stage: Test
      name: BDD
      script: 
        - behave