language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: redis-cli ping

script: python -m unittest test_server

#after_success:
#  - codecov

services:
  - redis-server
